### ISSUE TITLE
[FR] [ws-bulk-report-generator] Can not integrate with new Alerts reports

### ISSUE THREAD

**Issue by edwardhu** [whitesource-ps/ws-bulk-report-generator#11]
The current report generator can not get the new Alerts series reports.
Including "View By Vulnerability", "View By Vulnerability" and "Licensing & Compliance" reports.

For more details about the new reports, please follow the [Link](https://whitesource.atlassian.net/wiki/spaces/WD/pages/823099487/Moving+to+Security+Alerts+View+by+Vulnerability+Mode)

So here I raised a feature request to support the new Alert series reports.

**Comment by tamari-oz** [comment]
[Release 0.1.4.1](https://github.com/whitesource-ps/ws-bulk-report-generator/releases/tag/v0.1.4.1) should solve this issue. I also added PyPi package for easy deployment.

**Comment by Chiencc** [comment]
Hello tamari,

I've download the latest version project, and still can't download the view by vulnerability or view by library reports from the project
Have you verified that ?

Thanks.

![image](https://user-images.githubusercontent.com/59817890/143399788-91bf452e-7ac9-48aa-affc-870ff8fb95a3.png)

**Comment by tamari-oz** [comment]
1. There is no report type named **view_by_vulnerability** . You can see the full list of reports by executing the utility with `-h` switch. For "alerts" report - pass `-r alerts `.
2. There is a PyPi package for easy deployment, upgrade, etc... Just execute pip install ws-bulk-report-generator to obtain the latest release and following execute: `ws_bulk_report_generator -u <KEY> ...`/
3. If you still want to run this as a script, try to go back one dir level (to: ~/Downloads/ws-bulk-report-generator) and execute: `python3 ws_bulk_report_generator/bulk_report_generator.py -u...`.

Let me know if it helped.
