### ISSUE TITLE
[BUG] Can not integrate with new Alerts reports

### ISSUE THREAD

**Issue by Chiencc** [whitesource-ps/ws-bulk-report-generator#16]
Hello tamari,

*according to ticket : https://github.com/whitesource-ps/ws-bulk-report-generator/issues/11

I've download the latest version project, and still can't download the view by vulnerability or view by library reports from the project
Have you verified that ?

Thanks.

![image](https://user-images.githubusercontent.com/59817890/143543178-9bf3f9e2-52ed-474c-981d-bd3a3c02c519.png)

**Comment by tamari-oz** [comment]
1. There is no report type named **view_by_vulnerability** . You can see the full list of reports by executing the utility with `-h` switch. For "alerts" report  pass `-r alerts` .
2. There is a PyPi package for easy deployment, upgrade, etc... Just execute `pip install ws-bulk-report-generator` to obtain the latest release and following execute: `ws_bulk_report_generator -u <KEY> ...`.
3. If you still want to run this as a script, try to go back one dir level (to: _~/Downloads/ws-bulk-report-generator_) and execute: `python3 ws_bulk_report_generator/bulk_report_generator.py -u....`.

Let me know if it helped.

**Comment by tamari-oz** [comment]
Closing this. Please reopen if help is still necessary.
