### ISSUE TITLE
Q: How to get a list of product names that use a specific library and user names associated with that product?

### ISSUE THREAD

**Issue by what-about-sun** [whitesource-ps/ws-bulk-report-generator#38]
Hello,

I would like to know if a certain library is used within an organisation.
If so, I would like to have a list of the product names that use this library and the usernames (mail address) associated with this product.

This repo solves the first part of the request.

An automated solution for the second part would be very helpful:
One possibility could be: retrieve a list of users: `"requestType": "getProductAssignments"`.
This list then contains what we want to have now: "email": "user_email".

The request would be something like this: 
Show me in an organisation all product names that use a certain library and show me per product all assigned user names (mail addresses) - as Excel and/or JSON.

Thanks.

**Comment by tamari-oz** [comment]
The Bulk Report Generator tool is designed to run multiple report within an organization and either generate a seperate or unified output per run.
The next [WS-SDK ](https://github.com/whitesource-ps/ws-sdk/releases) version (> 0.8.2.2) will allow this tool to filter WS inventory report with a lib name (`...-r inventory -x name=<lib_name>`).

Unfortunately the ER you are requesting is not in the scope of this project.
I suggest you'll consult with your CSM to see options here.
