### ISSUE TITLE
[BUG] [ws-bulk-report-generator] "WARNING: ws-bulk-report-generator 0.2.1 does not provide the extra 'xslx'"

### ISSUE THREAD

**Issue by hugh-whitesource** [whitesource-ps/ws-bulk-report-generator#47]
**Bug Description**  
When trying to use the new unified_xlsx option, it says the xlsxwriter requirement is needed: `Report type is 'unified_xlsx' but package 'XlsxWriter' is not installed. Make sure the tool is installed with optional dependency: 'pip install ws-bulk_report_generator[xslx]'`.  When I run that pip command, I get the error `WARNING: ws-bulk-report-generator 0.2.1 does not provide the extra 'xslx'`

**Steps to Reproduce**  
1. `pyenv virtualenv ws-bulk-report-generator`
2. `pyenv activate ws-bulk-report-generator`
3. `cd ws-bulk-report-generator/`
4. `ws_bulk_report_generator -u xxxxx -k yyyyy -r alerts -t unified_xlsx -s product -o reportsNonBinary`

**Expected Behavior**  
Optional requirement installed and can use new feature

**Environment Details**  
 - OS: Ubuntu 20.04 in Microsoft WSL

**Comment by rammatzkvosky** [comment]
Hi @hugh-whitesource 
There was a typo with the `xslx`--> should have been `xlsx`

`'pip install ws-bulk_report_generator[xslx]'`
Will be changed to :
`'pip install ws-bulk_report_generator[xlsx]'`

**Comment by rammatzkvosky** [comment]
Hi @hugh-whitesource  , we decided to remove that warning message and you should not stumble it from the upcoming version.

**Comment by rammatzkvosky** [comment]
@hugh-whitesource - you can  check the [latest version](https://pypi.org/project/ws-bulk-report-generator/0.2.3/)
