### ISSUE TITLE
[FR] [ws-bulk-report-generator] Add Organization to Outputs for GlobalOrg Reports

### ISSUE THREAD

**Issue by jbnable** [whitesource-ps/ws-bulk-report-generator#49]
**Is your feature request related to a problem? Please describe.**  
Reports from the global org do not contain the organization for each product.

**Describe the solution you'd like**  
Provide organization (token and name) as datafields with each returned entry.

**Comment by jbnable** [comment]
Any update on this request? When trying to use the bulk report tool to track down dependencies, it's difficult to determine which organization they belong to.

**Comment by rammatzkvosky** [comment]
Hi @jbnable , this feature is in our roadmap, and will address it soon.
I will keep you updated upon the implementation

**Comment by rammatzkvosky** [comment]
Hi @jbnable, check out the [latest version](https://github.com/whitesource-ps/ws-bulk-report-generator/issues/organization) which adds the organization name for each record, so you can distinguish which organization it came from.

Thanks,

WhiteSource PS team

**Comment by jbnable** [comment]
It works, thanks!
