### ISSUE TITLE
[FR] [ws-bulk-report-generator] Global Org Vuln Report

### ISSUE THREAD

**Issue by jbnable** [whitesource-ps/ws-bulk-report-generator#57]
I would like to pull a Global org report for vulnerabilities.

This can be accomplished right now by running vulnerability reports for each org and combining them.

Command:  ws_bulk_report_generator.exe -a https://app.whitesourcesoftware.com -u user_token -k org_token -y globalOrganization -o output_folder -r vulnerability -t unified_xlsx

**Comment by rammatzkvosky** [comment]
Hi @jbnable, check out the [latest version](organization) which adds the organization name for each record, so you can distinguish which organization it came from.

Thanks,

WhiteSource PS team

**Comment by jbnable** [comment]
Works great, thanks!
