### ISSUE TITLE
[Question] [ws-bulk-report-generator] Question Topic

### ISSUE THREAD

**Issue by jm185435** [whitesource-ps/ws-bulk-report-generator#65]
**Question**  
Please help me with the command to generate the inventory report for all the Orgs in our Global Org.
I have got global org admin permissions.
I verified the documentation but couldn't find anything for the report for all the org.
https://github.com/whitesource-ps/ws-bulk-report-generator

**Environment Details**  
 Windows 10

**Comment by NatalyaDalid** [comment]
Hey @jm185435 ,

Here's the command for the globalOrg run:
# Execute Alerts report and get a unified JSON on all the organizations within a Global organization (Note: user must be defined in all the organization): 
`ws_bulk_report_generator -u <USER_KEY> -k <ORG_TOKEN> -o /tmp/reports/ -r inventory -t unified_json -y globalOrganization`

This cmd line is also exist in the README

Thanks,
Mend PS Team

**Comment by jm185435** [comment]
Thanks Natayla. It worked for me.
